#pragma once
#include "renderer/material.h"



// Vertices in the mesh data generated have a position and a normal, vertices are not shared and normals are just the face normals
GPUMesh MarchingCubesGenerateMesh(f32* densityMap, u32 densityMapWidth, u32 densityMapHeight, u32 densityMapDepth);
// Requires the given mesh data to be generated by a previous call to MarchingCubesGenerateMesh with the same density map dimensions
void MarchingCubesRegenerateMesh(GPUMesh* gpuMesh, f32* densityMap, u32 densityMapWidth, u32 densityMapHeight, u32 densityMapDepth);
